from pathlib import Path
import pandas as pd
OUT = "/home/claude/build/stage7_outputs"
import os; os.makedirs(OUT, exist_ok=True)

# ===========================================================================
# A. INDICATOR DICTIONARY
# ===========================================================================
indicators = [
    dict(indicator_id="IND01", name="High alert concentration (volume-adjusted)",
         description="Entity's alert rate is statistically elevated above the 16.0% portfolio base rate after requiring a minimum sample size",
         source_fields="alerts.subject_id, alerts.severity, transactions.customer_id/counterparty_id",
         calculation_logic="binomial test vs base rate, n>=15, one-sided p<0.01; capped contribution regardless of how far above threshold",
         evidence_category="3 - Descriptive relationship (statistically tested)",
         why_it_matters="Existing monitoring system has independently and repeatedly flagged this entity's activity",
         innocent_explanation="Legitimate complex trade pattern that happens to trip routine monitoring rules more often (e.g. higher-risk corridor mix by chance, larger transaction sizes)",
         false_positive_risk="Medium - alerts are themselves imperfect detectors with their own false-positive rate; concentration of alerts is not concentration of confirmed issues",
         weight_proposal="3 points (capped) if p<0.01 and n>=15; 1 point if p<0.05 and n>=10",
         validation_check="Reproduced independently in SQL (Stage 4) and Python (Stage 5); stable under product-mix, corridor-mix, segment, and time-period controls",
         allowed_in_framework="YES"),
    dict(indicator_id="IND02", name="Exclusive customer-counterparty cluster relationship",
         description="A customer conducts an unusually large share (>=80%) of its transaction volume/value with a small, entity-resolution-linked counterparty cluster (n<=5 members)",
         source_fields="transactions.customer_id/counterparty_id (network), entity-resolution cluster membership (Stage 6)",
         calculation_logic="Share of customer's txn count AND value with cluster members >= 80%",
         evidence_category="2 - Derived analytical fact",
         why_it_matters="Concentration risk is elevated when nearly all business runs through a small, potentially-related counterparty set rather than a diversified customer base",
         innocent_explanation="Exclusive distributor/agency/franchise agreement; single-supplier or single-buyer relationship is a normal commercial structure, especially for SME exporters",
         false_positive_risk="Medium - exclusivity alone is common in legitimate small-business trade relationships",
         weight_proposal="3 points (capped) if exclusivity >=95%; 2 points if 80-95%",
         validation_check="Network view (Stage 6) cross-checked against entity-resolution cluster membership; re-verified transaction-level exclusivity independently",
         allowed_in_framework="YES"),
    dict(indicator_id="IND03", name="Shared bank account (any)",
         description="Two or more counterparties share an identical bank_account_hash value",
         source_fields="counterparties.bank_account_hash",
         calculation_logic="Exact match, pairwise, self-join with id_a<id_b",
         evidence_category="2 - Derived analytical fact",
         why_it_matters="Shared banking detail is one of the stronger entity-resolution signals - harder to collide coincidentally than an address string",
         innocent_explanation="Shared corporate treasury/holding company banking arrangement across legitimately separate subsidiaries",
         false_positive_risk="Low-Medium",
         weight_proposal="2 points",
         validation_check="Cross-checked against email/phone match (Stage 6) to rule out simple duplicate-data-entry explanation before scoring",
         allowed_in_framework="YES"),
    dict(indicator_id="IND04", name="Shared bank account PLUS an independent attribute",
         description="A shared-bank-account pair also shares registered_address, a declared relationship, or a near-duplicate name - i.e. Stage 6 'STRONG' classification",
         source_fields="counterparties.bank_account_hash, registered_address, legal_name; entity_relationships",
         calculation_logic="Stage 6 classification = STRONG AND does not also match on email/phone (i.e. excludes CL003-type duplicate signature)",
         evidence_category="2 - Derived analytical fact",
         why_it_matters="Convergence of two independent identifiers substantially reduces the coincidence explanation versus either alone",
         innocent_explanation="Same corporate family using shared registered-agent services and shared group banking",
         false_positive_risk="Low-Medium",
         weight_proposal="+1 bonus point on top of IND03 (i.e. STRONG pairs score 3 total, capped)",
         validation_check="Explicit exclusion of email/phone-matching pairs (duplicate signature) from this indicator, per Stage 6 finding",
         allowed_in_framework="YES"),
    dict(indicator_id="IND05", name="Declared relationship overlap (standalone)",
         description="A counterparty pair has a declared Entity_Relationships edge but no shared bank account",
         source_fields="entity_relationships.relationship_type/source",
         calculation_logic="Declared edge present, IND03 absent",
         evidence_category="7 (if source='regulatory_filing') or 4 (if source='declared', i.e. self-reported)",
         why_it_matters="A documented corporate link, even without shared banking, is relevant context for network read-across",
         innocent_explanation="Ordinary declared group structure with no bearing on transaction risk",
         false_positive_risk="Low (it's a documented fact) but LOW RELEVANCE risk is high - a declared link by itself says little about transaction risk",
         weight_proposal="1 point",
         validation_check="Distinguish source='regulatory_filing' (more reliable) from source='declared' (self-reported, lower reliability) - both scored the same here pending better provenance data",
         allowed_in_framework="YES"),
    dict(indicator_id="IND06", name="Value/weight implausibility",
         description="Invoice value per declared shipment kg is a large multiple of the product category's average",
         source_fields="transactions.invoice_value, shipments.declared_weight_kg, products.product_category",
         calculation_logic="ratio-vs-category-mean, threshold sensitivity-tested at 3x/5x/10x/20x/50x (Stage 5); framework uses the 3-method-STABLE set (ratio AND robust-z AND IQR agree) as the qualifying condition, not a single fixed cut",
         evidence_category="3 - Descriptive relationship (threshold-dependent)",
         why_it_matters="May indicate mis-invoicing, mis-declared goods, or valuation manipulation",
         innocent_explanation="Legitimate high-value/low-weight goods (electronics, pharma actives), unit/currency entry variance, premium product variant",
         false_positive_risk="Medium-High - Stage 5 showed candidate count ranges 22 to 157 depending on method/threshold",
         weight_proposal="2 points (capped) - only for the 85-transaction STABLE set common to all 3 detection methods",
         validation_check="Threshold sensitivity table retained and shown alongside any flagged transaction - never presented as a single fixed number",
         allowed_in_framework="YES"),
    dict(indicator_id="IND07", name="Third-party payer route",
         description="Final settlement leg paid by an entity other than the customer",
         source_fields="payments.paying_entity_type",
         calculation_logic="paying_entity_type != 'customer'",
         evidence_category="1 - Observed fact",
         why_it_matters="Occasionally associated with layering in genuine financial-crime typologies",
         innocent_explanation="Factoring, group treasury consolidation, assigned receivables - all standard trade-finance practice",
         false_positive_risk="High - Stage 5 found the apparent 100% alert co-occurrence for this indicator is CIRCULAR (alert_type restates the same fact) and must not be double-counted",
         weight_proposal="1 point MAXIMUM - explicitly low/moderate per instruction, and must not be combined with any alert-based bonus for the same transaction",
         validation_check="Confirmed circularity in Stage 5; framework scoring code explicitly excludes IND01 alert bonus from stacking with IND07 for the same transaction",
         allowed_in_framework="YES, capped low"),
    dict(indicator_id="IND08", name="Claim with prior alert",
         description="A claim's underlying transaction had >=1 alert on record before the claim",
         source_fields="claims.transaction_id, alerts.subject_id/alert_date",
         calculation_logic="EXISTS alert for the same transaction_id",
         evidence_category="3 - Descriptive relationship (strong at portfolio level, not causal)",
         why_it_matters="Combines two independent monitoring/outcome signals on the same transaction",
         innocent_explanation="Both alerts and claims may independently reflect the same underlying transaction complexity or counterparty risk profile, without one causing the other",
         false_positive_risk="Medium - portfolio-level relationship is robust (Stage 5, chi2 p=1.2e-18) but any single instance could be coincidental",
         weight_proposal="1 point",
         validation_check="Portfolio relationship re-verified in Stage 5 across segment and value-band strata",
         allowed_in_framework="YES"),
    dict(indicator_id="IND09", name="Date/data-quality issue exposure",
         description="Entity's transactions are disproportionately affected by logged Stage 3 data-quality issues (date-logic errors, missing values)",
         source_fields="data_quality_issues table; shipments/payments date-logic flags",
         calculation_logic="Share of entity's transactions affected by a DQ0001/DQ0002-type issue vs portfolio rate",
         evidence_category="6 - Intelligence gap (NOT an aggravating risk signal)",
         why_it_matters="Reduces confidence in any OTHER indicator computed on the same records - a caveat, not evidence of anything",
         innocent_explanation="Routine data entry error, system lag, incomplete shipment record",
         false_positive_risk="N/A - this indicator only ever REDUCES confidence, never increases priority",
         weight_proposal="0 points; applied as a CONFIDENCE DISCOUNT modifier only",
         validation_check="Cross-referenced against Stage 3 issue register by table/record",
         allowed_in_framework="YES, as a discount modifier only - never a positive score contributor"),
    dict(indicator_id="IND10", name="Intermediary hub concentration",
         description="An intermediary handles a disproportionate share of portfolio transaction volume",
         source_fields="transaction_intermediaries.intermediary_id",
         calculation_logic="Share of distinct linked transactions handled by one intermediary",
         evidence_category="3 - Descriptive relationship (concentration is a fact; risk is not)",
         why_it_matters="COULD indicate a chokepoint entity of interest - but ONLY if combined with independent indicators on the SAME intermediary",
         innocent_explanation="Ordinary large-scale freight-forwarder/correspondent-bank serving a broad, undifferentiated client base (this is what Stage 6 found for INTM00038)",
         false_positive_risk="Very high if scored on centrality alone - explicitly the trap this framework must not fall into",
         weight_proposal="0 points from concentration alone. Only scores if the SAME intermediary independently shows an elevated alert/claim rate vs baseline (which INTM00038 does not: 16.01%/3.04% vs 16.0%/3.0% baseline)",
         validation_check="Stage 6 explicitly tested INTM00038's alert/claim rate against baseline and found no elevation - EXCLUDED from scoring on this basis",
         allowed_in_framework="YES, but gated - contributes 0 points unless a companion condition (elevated own alert/claim rate) is independently met"),
]
ind_df = pd.DataFrame(indicators)
ind_df.to_csv(f"{OUT}/7a_indicator_dictionary.csv", index=False)
print(f"Indicator dictionary: {len(ind_df)} indicators defined, all ALLOWED into framework (IND09 as discount-only, IND10 as gated-only)")
print(ind_df[["indicator_id","name","weight_proposal","allowed_in_framework"]].to_string(index=False))
