from pathlib import Path
import pandas as pd
OUT = "/home/claude/build/stage9_outputs"

claims = [
    dict(claim_id="CL-A", claim_statement="CUST00135/CL001 should be prioritised for EDD review",
         evidence_for="100% alert rate (38/38 txns, p=5.7e-31 vs 16% base); 100% transactional/value exclusivity to a 4-member counterparty cluster; cluster is STRONG entity-resolution classified (shared bank account + address, 2/6 pairs also declared shared_director from regulatory_filing source); pattern survives product-mix, corridor-mix, segment, and time-period controls (Stage 5); independently reproduced in SQL and Python",
         evidence_against="2 of 6 cluster pairs have a DECLARED (documented) relationship, which is consistent with disclosed group structure rather than concealment; no sanctions-type or violence-related indicator present anywhere in this dataset; claim outcomes for the cluster are modest (2 claims)",
         alternative_explanation="Exclusive distributor/agency agreement with a related corporate family sharing group treasury banking - a normal, legal SME commercial structure",
         sample_size_base_rate="n=38 transactions (customer), n=125 transactions (cluster); base rate for comparison 16.0% portfolio alert rate",
         sensitivity_test_result="Removing alert indicators: cluster+exclusivity alone still scores 6/6, customer remains top-ranked (Stage 7 stress test). Removing entity-resolution indicators: customer ties with 1 other on capped score, but p-value differentiates by 27 orders of magnitude.",
         confidence_rating="High (statistical) / Low (as to cause)",
         final_status="CARRY FORWARD - as an EDD referral for review, explicitly not as a finding of wrongdoing"),
    dict(claim_id="CL-B", claim_statement="CUST00070/CL002 should be prioritised for EDD review",
         evidence_for="Same structural pattern as CL-A: 100% alert rate (37/37, p=3.6e-30), 100% exclusivity to a 4-member STRONG-classified cluster",
         evidence_against="Declared relationship for this cluster is source='declared' (self-reported), a WEAKER provenance than CL-A's regulatory_filing source - this specific reassurance is less reliable here",
         alternative_explanation="Same as CL-A",
         sample_size_base_rate="n=37 transactions (customer), n=115 (cluster)",
         sensitivity_test_result="Identical stress-test behaviour to CL-A (Stage 7)",
         confidence_rating="High (statistical) / Low (as to cause)",
         final_status="CARRY FORWARD - EDD referral, with explicit note that the declared relationship here is lower-provenance than CL-A's"),
    dict(claim_id="CL-C", claim_statement="Case C (85-txn value/weight set) requires further data or review",
         evidence_for="Stable under 3 independent detection methods (ratio/robust-z/IQR); alert rate 38.8% vs 15.7% rest-of-portfolio base rate is now CONFIRMED ROBUST after this session's stratified test - holds across every product category, corridor, and segment stratum with an observation (Mid-market 58% vs 15.6%, SME 29% vs 16.4%, Corporate 50% vs 13.1%, Corridor_F 45% vs 15.5%, etc.)",
         evidence_against="No customer/counterparty concentration (max 3/85 any customer, max 2/85 any counterparty) - rules out a single-actor explanation; payment and shipment value reconciliation is PERFECT (0 mismatches) - the anomaly is confined to the weight dimension only; DQ cross-check shows NO elevation in date-logic errors (0% vs 1.0%/0.6% baseline) or entity-resolution cluster overlap (27% vs 28.8% baseline) - rules out both a data-error and an entity-resolution explanation; missing-arrival-date (3.5% vs 2.0%) and partial-payment (18.8% vs 15.0%) rates are only mildly and not significantly elevated on n=85",
         alternative_explanation="Ordinary within-category value variance (premium/bespoke goods vs standard grade) spread across many unrelated customers/counterparties; the elevated alert rate could reflect that Northbridge's OWN existing monitoring system already targets value/weight-type anomalies specifically (a form of the same circularity risk flagged for IND07, not yet ruled out here)",
         sample_size_base_rate="n=85 of 6000 (1.4%); category/corridor/segment sub-cells often n<5, too small to test individually beyond noting directional consistency",
         sensitivity_test_result="Gap-closure testing (this session) ELIMINATED the data-quality and entity-resolution explanations and CONFIRMED the alert-rate elevation is not a confound artifact. Circularity check (performed this session): of 33 alerts on Case C transactions, 23 (70%) are typed 'value_mismatch' - plausibly definitionally related to the same ratio calculation and a PARTIAL circularity risk, similar in kind to (but weaker than) the fully-circular IND07 case; the remaining 30% are independent alert types (high_value_threshold, third_party_payment, repeat_counterparty_flag, documentation_gap, unusual_routing, late_shipment), so this is NOT fully circular like IND07 was.",
         confidence_rating="Medium (statistical pattern) - increased from Stage 8's Medium given confounds are now ruled out, but capped at Medium pending the new circularity check",
         final_status="REQUIRES MORE DATA - now narrowed to ONE substantive gap: product-specialist plausibility review of goods value/weight. The circularity concern is PARTIAL (70% of alerts share a plausibly-related type) rather than fully resolved or fully circular, and is noted as a caveat on the 38.8% alert-rate figure rather than grounds to discard it."),
    dict(claim_id="CL-D", claim_statement="Third-party payer indicator should not be over-weighted",
         evidence_for="Stage 5 found TP-payer transactions show 100% alert co-occurrence, but every one of those alerts is typed exactly 'third_party_payment' - i.e. the alert restates the same underlying payment-routing fact rather than providing independent corroboration",
         evidence_against="None - this is a confirmed circularity, not a contested finding",
         alternative_explanation="N/A - the circularity itself is the finding",
         sample_size_base_rate="n=120 TP-payer transactions (2.0% of portfolio); claim rate for this group 5.0% vs 2.96% non-TP (a real but modest difference)",
         sensitivity_test_result="Stage 7 framework explicitly caps IND07 at 1 point and bars it from stacking with any alert-based bonus for the same transaction - re-verified in Stage 7's scoring code this session's review",
         confidence_rating="High confidence the circularity is real; Low confidence TP-payer status alone carries meaningful risk signal",
         final_status="CARRY FORWARD - capped/low-weight only, exactly as designed; do not raise its weight"),
    dict(claim_id="CL-E", claim_statement="Claim/prior-alert relationship is descriptive, not causal",
         evidence_for="Chi-square test significant (p=1.2e-18); holds directionally across SME/Mid-market segments and all 4 value-quartiles (Stage 5)",
         evidence_against="Corporate segment (n=46 alerted) and several corridor cells too thin to confirm independently",
         alternative_explanation="Both alerts and claims may independently track shared underlying transaction/counterparty complexity or exposure, rather than one causing the other - no mechanism has been identified or tested",
         sample_size_base_rate="n=960 alerted / n=5040 non-alerted transactions; claim rate 7.50% vs 2.14%",
         sensitivity_test_result="Re-verified this session: relationship direction is consistent in every stratum tested with adequate n; no stratum reverses the direction",
         confidence_rating="Strong descriptive relationship (portfolio and SME/Mid-market level); Weak/insufficient at Corporate-segment level",
         final_status="CARRY FORWARD - explicitly labelled non-causal in any report; Corporate-segment figure excluded from headline reporting due to insufficient n"),
    dict(claim_id="CL-F", claim_statement="INTM00038 should be cleared as an ordinary hub",
         evidence_for="66.5% of linked-transaction volume but own alert rate 16.01% and claim rate 3.04% - statistically indistinguishable from portfolio baseline (16.0%/3.0%); touches all 180 customers and all 260 counterparties (maximum possible diversity); no entity-resolution cluster membership",
         evidence_against="None identified",
         alternative_explanation="N/A - 'ordinary large-scale freight forwarder' is the leading and only well-supported explanation",
         sample_size_base_rate="n=3,360 distinct linked transactions - the largest sub-sample of any entity in the portfolio, giving high statistical confidence in its baseline-matching rates",
         sensitivity_test_result="Stage 7's IND10 gate re-tested this session: gate condition (elevated own alert/claim rate) confirmed still FAILS; 0 points under the framework",
         confidence_rating="High confidence this is an ordinary service provider",
         final_status="CARRY FORWARD as a documented clearance - explicitly retained in the executive report as a negative finding, not silently dropped"),
    dict(claim_id="CL-G", claim_statement="CL003 duplicate-like cluster should be treated as a data-quality issue, not an investigation lead",
         evidence_for="15 pairs (+1 triple) match on EVERY attribute tested including incidental fields (email, phone) that would not plausibly be shared by genuinely distinct legitimate entities; no alert/claim rate elevation for this group; no customer concentration",
         evidence_against="None identified",
         alternative_explanation="N/A - 'duplicate data entry of the same real-world entity' is the leading and only well-supported explanation, distinguished specifically by the email/phone match that CL001/CL002 do NOT show",
         sample_size_base_rate="15 pairs + 1 three-way group = 38 counterparty records out of 260",
         sensitivity_test_result="Cross-checked this session: 20 of the 85 Case C counterparties overlap SOME entity-resolution cluster, but at a rate (27%) matching the portfolio baseline (28.8%) - confirms these overlaps are not concentrated or meaningful",
         confidence_rating="High confidence this is a data-quality artifact",
         final_status="CARRY FORWARD to data-quality remediation (Stage 3 issue register), REMOVED from investigative candidate lists"),
    dict(claim_id="CL-H", claim_statement="Priority score is a review-ordering tool, not proof of wrongdoing",
         evidence_for="Framework is fully explainable (Stage 7 indicator dictionary); every score traces to named source fields and calculation logic; no indicator alone can reach High band (max single-indicator contribution = 3 of 10); stress tests (Stage 7) confirm no single indicator dominates and that centrality-only signals (INTM00038) cannot score",
         evidence_against="A reader viewing only the score/band column without the accompanying evidence and alternative-explanation columns could misread 'High priority' as a finding",
         alternative_explanation="N/A - this is a framework-design claim, not an empirical one",
         sample_size_base_rate="N/A",
         sensitivity_test_result="Stage 7 stress tests 1-5 all confirm the framework behaves as designed (indicators removable individually without collapsing top candidates' evidence trail; caps enforced; gated indicators correctly exclude INTM00038)",
         confidence_rating="High confidence in the framework's internal consistency",
         final_status="CARRY FORWARD, with a MANDATORY reporting requirement: priority band must never be displayed without its accompanying evidence/alternative-explanation/confidence columns in any dashboard or executive view"),
]
reg = pd.DataFrame(claims)
reg.to_csv(f"{OUT}/9b_claim_control_register.csv", index=False)
print(reg[["claim_id","confidence_rating","final_status"]].to_string(index=False))
